apiVersion: v1
kind: Service
metadata:
  labels:
    app: giropops
  name: giropops
  namespace: default
spec:
  clusterIP: 10.96.61.48
  clusterIPs:
  - 10.96.61.48
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30887
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: giropops
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 144.22.226.100